# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
    ]
