# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0002_auto_20160220_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(default=datetime.datetime(2016, 2, 20, 1, 43, 15, 730882, tzinfo=utc), upload_to='media/pais/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
