# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0005_auto_20160220_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/pais/'),
        ),
    ]
