# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Aerolinea')),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destino.Destino')),
            ],
        ),
    ]
