# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Vuelo')),
            ],
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='pais',
            field=models.CharField(choices=[('EU', 'ESTADOS UNIDOS'), ('MX', 'MEXICO'), ('AU', 'AUSTRALIA'), ('FR', 'FRANCIA'), ('BR', 'BRASIL'), ('SA', 'SUDAFRICA'), ('SP', 'ESPAÑA')], max_length=2),
        ),
    ]
