# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 02:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0004_auto_20160220_0143'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aerolinea',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
